config/routes.rb
Kandan::Application.routes.draw do

  devise_for :users, :controllers => {
    :sessions => "sessions"
  }
  devise_scope :user do
    authenticated :user do
      root :to => "main#index"

      get '/search' => "main#search"

      resources :channels do
        resources :activities
        resources :attachments
      end

      resources :users, :only => [:index, :show]

      get "/active_users" => "apis#active_users"
      get "/me" => "apis#me"

      get "/users/edit" =>"main#users_edit"

      namespace :admin do
        root :to => "admin#index"
        post "/update", :to => "admin#update", :as => "update"
        post "/update_user", :to => "admin#update_user", :as => "update_user"
        post "/toggle_admin", :to => "admin#toggle_admin"
      end
    end

    unauthenticated do
      root to: "sessions#new"
    end
  end

  # Pages Controller
  get "/approval", :to => "pages#approval"
  get "/suspended", :to => "pages#suspended"
  get "/about", :to =>"pages#about"

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    # TODO this isn't being used right now. use this for faster app
    @channels = Channel.includes(:activities => :user).all
  end

  def search
    minimum_query_length = 3

    if params[:query] and params[:query].length >= minimum_query_length
      @activities = Activity.includes(:user).where("LOWER(content) LIKE ?", "%#{params[:query]}%").limit(params[:limit] || 100).all
    end

    respond_to do |format|
      format.html
      format.json { render :json => @activities.to_json(:include => :user) }
    end
  end
end

app/views/main/_nav.html.erb
<nav class="nav">
  <form class="search" method="get" action="/search">
    <input type="text" class="query" name="query" value="<%= params[:query].presence || "" %>" />
    <input type="submit" class="submit" value="Search">
  </form>
  <ul id="channel_nav"></ul>
</nav>

app/views/main/_sidebar.html.erb
<div class="header user-header">
  <a href="#" class="user-menu-toggle">
    <img src="<%= avatar_url_for(current_user, :size => 25) %>"/>
    <i class="icon-angle button right"></i>
    <%= current_user.full_name_or_username %>
  </a>
  <ul class="user-menu">
    <li><%= link_to 'Admin console', admin_root_path if current_user.is_admin? %></li>
    <li><%= link_to 'Edit Account', users_edit_path %></li>
    <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
    <li><%= link_to 'About Kandan', about_path %></li>
  </ul>
</div>
<div class="widgets"></div>

app/views/main/index.html.erb
<% content_for :header do %>
  <a href="#" class="nav-toggle button left"><i class="icon-comments"></i></a>
  <a href="#" class="sidebar-toggle button right"><i class="icon-reorder"></i></a>
<% end %>

<% content_for :sidebar, render("sidebar") %>

<div id="channels"></div>

<% content_for :end do %>
  <%= render "nav" %>

  <%= javascript_tag do %>
    $(document).ready(function(){
      Kandan.init()
    })
  <%- end %>

  <%- Kandan::Config.broadcaster.assets.each do |asset| %>
    <%= javascript_include_tag asset %>
  <%- end %>

  <%= javascript_tag do %>
    $(document).data("active-users", [])
  <%- end %>

  <ul class="audio_channels" style="display:none;">
    <audio class="audio_private"></audio>
    <audio class="audio_common"></audio>
  </ul>
<% end %>

app/views/main/search.html.erb
<% content_for :header do %>
  <%= link_to content_tag(:i, nil, class: 'icon-angle-left'), root_path, class: 'button left' %>
<% end %>

<%= javascript_tag do %>
  $(document).ready(function(){
    Kandan.Plugins.initAll()
    activities = <%= json_escape(@activities.as_json(:include => { user: { :only => [:email, :first_name, :last_name, :username, :avatar_url, :gravatar_hash, :is_admin]} }).to_json.html_safe) %>;

    if(activities.length){
      $.each(activities, function(index, activityAttributes) {
        activity = new Kandan.Models.Activity(activityAttributes);
        activityView = new Kandan.Views.ShowActivity({activity: activity});
        $(".activities").append(activityView.render().el);
      })
    }else{
      $(".activities").append("<div class='no-results'><h2>No search results for '<%= params[:query] %>'</h2></div>");
    }

  })
<%- end %>

<div class="activities"></div>

<% content_for :end do %>
  <%= render "nav" %>
<% end %>