config/routes.rb
Kandan::Application.routes.draw do

  devise_for :users, :controllers => {
    :sessions => "sessions"
  }
  devise_scope :user do
    authenticated :user do
      root :to => "main#index"

      get '/search' => "main#search"

      resources :channels do
        resources :activities
        resources :attachments
      end

      resources :users, :only => [:index, :show]

      get "/active_users" => "apis#active_users"
      get "/me" => "apis#me"

      get "/users/edit" =>"main#users_edit"

      namespace :admin do
        root :to => "admin#index"
        post "/update", :to => "admin#update", :as => "update"
        post "/update_user", :to => "admin#update_user", :as => "update_user"
        post "/toggle_admin", :to => "admin#toggle_admin"
      end
    end

    unauthenticated do
      root to: "sessions#new"
    end
  end

  # Pages Controller
  get "/approval", :to => "pages#approval"
  get "/suspended", :to => "pages#suspended"
  get "/about", :to =>"pages#about"

end

app/views/admin/admin/_user.html.erb
<li class="user" data-user-id="<%= user.id%>" data-full-name="<%= user.full_name_or_username %>">
  <%= image_tag avatar_url_for(user, :size => 70), class: 'avatar' %>
  <div class="name">
    <% if user.full_name.blank? %>
      <%= user.username %>
    <% else %>
      <%= "#{user.full_name} (#{user.username})" %>
    <% end %>
  </div>
  <div class="email-and-status">
    <span class="email"><%= user.email %></span> <%= user_status_badge(user) %>
  </div>
  <div>
    <%= user_status_button(user) %>
    <%= user_admin_button(user) %>
  </div>
</li>

app/views/admin/admin/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "admin/admin" %>
<% end %>

<% content_for :header do %>
  <%= link_to content_tag(:i, nil, class: 'icon-angle-left'), root_path, class: 'button left' %>
<% end %>

<div class="admin">
  <div class="site-settings">
    <h3>Site settings</h3>
    <%= form_for @settings, :url => admin_update_path, :method => :post do |f| %>
      <%= f.label :max_rooms do %>
        Max number of rooms <%= f.number_field :max_rooms, :class => "input-mini pull-right" %>
      <% end %>

      <%= f.label :disable_conn_disconn_activity do %>
        <%= f.check_box :disable_conn_disconn_activity, :class => "switch" %> disable connect/disconnect activity
        <span></span>
      <% end %>

      <%= f.label :public_site do %>
        <%= f.check_box :public_site, :class => "switch" %> Public site
        <span></span>
      <% end %>
      <p>
        <%= f.submit :class => "btn btn-success" %>
      </p>
    <% end %>
  </div>
  <div class="waiting-for-approval-users">
    <h3>Users waiting for approval</h3>
    <ul class="users">
      <%= render(:collection => @waiting_for_approval_users, :as => :user, :partial => "user") ||\
        content_tag(:li, "There are no users needing approval right now. Invite others to join Kandan!", class: 'no-users') %>
    </ul>
  </div>
  <div class="approved-users">
    <h3>All users</h3>
    <ul class="users">
      <%= render(:collection => @approved_users, :as => :user, :partial => "user") ||\
        content_tag(:li, "There are no users. Invite others to join Kandan!", class: 'no-users') %>
    </ul>
  </div>
</div>